### ISSUE TITLE
Getting [!] Some python modules are missing!  erro

### ISSUE THREAD

**Issue by gopinath6** [Smaash/snitch#2]
Am using python 2.7 on win7 am getting below error message.Any help?

[!] Some python modules are missing!

**Comment by Smaash** [comment]
I thnk that you dont have 'socks' module installed, try to remove it from import list.

**Comment by Smaash** [comment]
Fixed in 0.3.2.

**Comment by LodeVanB** [comment]
In snitch 0.3.2 I still get the error of missing socks, tried pip install socks but this wasn't available, subsequent socks5 and socksonsocks was to no avail while ran, but after a wait I got results; HTH
